In [43]:
import numpy as np
from scipy.io import loadmat
import matplotlib.pyplot as plt 
import math

def gram_schmidt(B):
    """Orthogonalize a set of vectors stored as the columns of matrix B."""
    # Get the number of vectors.
    m, n = B.shape
    # Create new matrix to hold the orthonormal basis
    U = np.zeros([m,n]) 
    for j in range(n):
        # To orthogonalize the vector in column j with respect to the
        # previous vectors, subtract from it its projection onto
        # each of the previous vectors.
        v = B[:,j].copy()
        for k in range(j):
            v -= np.dot(U[:, k], B[:, j]) * U[:, k]
        if np.linalg.norm(v)>1e-10:
            U[:, j] = v / np.linalg.norm(v)
    return U

if __name__ == '__main__':
    B1 = np.array([[1.0, 1.0, 0.0], [2.0, 2.0, 0.0], [2.0, 2.0, 1.0]])
    A1 = gram_schmidt(B1)
    # print(A1)
    A2 = gram_schmidt(np.random.rand(4,2)@np.random.rand(2,5))
    # print(A2.transpose()@A2)


    in_data = loadmat('movie.mat')
    M = in_data['M']
 
ones_column = np.ones((M.shape[0], 1))

# Add the ones column to the beginning of M
M_new = np.hstack((ones_column, M))
# print(M_new)


# B3 = np.array([
#     [1.0,1.0,1.0,1.0,1.0],  [7.0,3.0,8.0,2.0,9.0], [4.0,9.0,4.0,9.0,4.0], [2.0,5.0,3.0,6.0,2.0], [8.0,6.0,7.0,5.0,8.0], [7.0,10.0,6.0,9.0,7.0], [4.0,5.0,4.0,5.0,4.0], [2.0,5.0,1.0,4.0,1.0]

# ])
# print (B3)
# B4 = np.transpose(B3)
# print (B4)
# print(gram_schmidt(B4))
# print(np.transpose(gram_schmidt(B4)))

# a = math.sqrt(5)
# b = math.sqrt(30)
# c = math.sqrt(10)
# T = np.array([
#     [1/a, -b/15, -c/5],[1/a, b/10, c/10], [1/a, -b/15, 0], [1/a, b/10, -c/10], [1/a, -b/15, c/5]
# ])

np.set_printoptions(precision=4, suppress=True)
X_1 = np.array([
    [2,5,8],[1,5,9],[1,0,8]
])
a = math.sqrt(3)
b = math.sqrt(2)
c = math.sqrt(6)



T_1 = np.array([
    [1/a, -b/2, c/6], [1/a, 0, -c/3], [1/a, 1/b, 1/c]
])
x_2 = np.array([[1,0,8],[2,5,8],[1,5,9]])
d = math.sqrt(3)
e = math.sqrt(38)
f = d = math.sqrt(114)

T_2 = np.array(
    [[1/a, -b/19, -4*(c)/57], [1/a, -3*(b)/38, 7*(c)/114], [1/a, 5*(b)/38, c/114]]
)


T_T = np.transpose(T_2)
mult = np.dot(T_T, T_2)
inverse = np.linalg.inv(mult)
w = np.dot(inverse, T_T)
w = np.dot(w, x_2)
print((w))
print("\n")

print(np.dot(T_2, w))
print("\n")











[[ 2.3094  5.7735 14.4338]
 [-2.1213  7.0711  3.5355]
 [ 2.8577 16.3299  0.4082]]


[[ 1. -0.  8.]
 [ 2.  5.  8.]
 [ 1.  5.  9.]]


